# Generated by Django 2.2.14 on 2021-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_expected_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expected_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
