# Generated by Django 2.2.14 on 2020-07-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200711_0551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='expected_pric',
            new_name='expected_price',
        ),
    ]
